
["Item Drop Weight Settings for Latiao Bonus Bag X / 辣条福袋X 物品抽取权重设置"]
	#Weight: Chiren Chen's Latiao / 权重：「赤刃」的辣条
	#Range: 0 ~ 512
	WeightCHIRENCHENLatiao = 5
	#Weight: TH_my's Latiao / 权重：「裂纹虎克」的辣条
	#Range: 0 ~ 512
	WeightTHMYLatiao = 5
	#Weight: SJKD's Latiao / 权重：「SJKD」的辣条
	#Range: 0 ~ 512
	WeightSJKDLatiao = 5
	#Weight: Mikhail Tapio's Latiao / 权重：「北斗余晖」的辣条
	#Range: 0 ~ 512
	WeightPLRLatiao = 5
	#Weight: Ginger Meow's Latiao / 权重：「姜喵」的辣条
	#Range: 0 ~ 512
	WeightGINGERMEOWLatiao = 5
	#Weight: CWQS's Latiao / 权重：「汽水」的辣条
	#Range: 0 ~ 512
	WeightCWQSLatiao = 5
	#Weight: Daiyousei's Latiao / 权重：「大妖精」的辣条
	#Range: 0 ~ 512
	WeightDaiyouseiLatiao = 5

["Item Drop Count Settings for Latiao Bonus Bag X / 辣条福袋X 物品抽取数量设置"]
	#Count: Chiren Chen's Latiao / 数量：「赤刃」的辣条
	#Range: 0 ~ 64
	CountCHIRENCHENLatiao = 1
	#Count: TH_my's Latiao / 数量：「裂纹虎克」的辣条
	#Range: 0 ~ 64
	CountTHMYLatiao = 1
	#Count: SJKD's Latiao / 数量：「SJKD」的辣条
	#Range: 0 ~ 64
	CountSJKDLatiao = 1
	#Count: Mikhail Tapio's Latiao / 数量：「北斗余晖」的辣条
	#Range: 0 ~ 64
	CountPLRLatiao = 1
	#Count: Ginger Meow's Latiao / 数量：「姜喵」的辣条
	#Range: 0 ~ 64
	CountGINGERMEOWLatiao = 1
	#Count: CWQS's Latiao / 数量：「汽水」的辣条
	#Range: 0 ~ 64
	CountCWQSLatiao = 1
	#Count: Daiyousei's Latiao / 数量：「大妖精」的辣条
	#Range: 0 ~ 64
	CountDaiyouseiLatiao = 1

