// client_scripts/gtm_voltage_fix.js
ClientEvents.lang(event => {
    // 基本缩写
    event.rename("material.ulv", "凝气");
    event.rename("material.lv", "筑基");
    event.rename("material.mv", "结丹");
    event.rename("material.hv", "元婴");
    event.rename("material.ev", "化神");
    event.rename("material.iv", "婴变");
    event.rename("material.luv", "问鼎");
    event.rename("material.zpm", "窥涅");
    event.rename("material.uv", "净涅");
    event.rename("material.uhv", "碎涅");
    event.rename("material.uev", "空涅");
    event.rename("material.uiv", "空灵");
    event.rename("material.uxv", "空玄");
    event.rename("material.opv", "空劫");
    event.rename("material.max", "踏天");

    // 电压等级键
    event.rename("gtceu.voltage.ulv", "凝气");
    event.rename("gtceu.voltage.lv", "筑基");
    event.rename("gtceu.voltage.mv", "结丹");
    event.rename("gtceu.voltage.hv", "元婴");
    event.rename("gtceu.voltage.ev", "化神");
    event.rename("gtceu.voltage.iv", "婴变");
    event.rename("gtceu.voltage.luv", "问鼎");
    event.rename("gtceu.voltage.zpm", "窥涅");
    event.rename("gtceu.voltage.uv", "净涅");
    event.rename("gtceu.voltage.uhv", "碎涅");
    event.rename("gtceu.voltage.uev", "空涅");
    event.rename("gtceu.voltage.uiv", "空灵");
    event.rename("gtceu.voltage.uxv", "空玄");
    event.rename("gtceu.voltage.opv", "空劫");
    event.rename("gtceu.voltage.max", "踏天");

    // 机械方块
    event.rename("block.gtceu.ulv_machine_casing", "§8凝气§r机械方块");
    event.rename("block.gtceu.lv_machine_casing", "§7筑基§r机械方块");
    event.rename("block.gtceu.mv_machine_casing", "§b结丹§r机械方块");
    event.rename("block.gtceu.hv_machine_casing", "§6元婴§r机械方块");
    event.rename("block.gtceu.ev_machine_casing", "§5化神§r机械方块");
    event.rename("block.gtceu.iv_machine_casing", "§9婴变§r机械方块");
    event.rename("block.gtceu.luv_machine_casing", "§d问鼎§r机械方块");
    event.rename("block.gtceu.zpm_machine_casing", "§c窥涅§r机械方块");
    event.rename("block.gtceu.uv_machine_casing", "§3净涅§r机械方块");
    event.rename("block.gtceu.uhv_machine_casing", "§4碎涅§r机械方块");
    event.rename("block.gtceu.uev_machine_casing", "§a空涅§r机械方块");
    event.rename("block.gtceu.uiv_machine_casing", "§2空灵§r机械方块");
    event.rename("block.gtceu.uxv_machine_casing", "§e空玄§r机械方块");
    event.rename("block.gtceu.opv_machine_casing", "§9§l空劫§r机械方块");
    event.rename("block.gtceu.max_machine_casing", "§c§l踏天§r机械方块");

    // 机器外壳
    event.rename("block.gtceu.ulv_machine_hull", "§8凝气§f机器外壳");
    event.rename("block.gtceu.lv_machine_hull", "§7筑基§f机器外壳");
    event.rename("block.gtceu.mv_machine_hull", "§b结丹§f机器外壳");
    event.rename("block.gtceu.hv_machine_hull", "§6元婴§f机器外壳");
    event.rename("block.gtceu.ev_machine_hull", "§5化神§f机器外壳");
    event.rename("block.gtceu.iv_machine_hull", "§9婴变§f机器外壳");
    event.rename("block.gtceu.luv_machine_hull", "§d问鼎§f机器外壳");
    event.rename("block.gtceu.zpm_machine_hull", "§c窥涅§f机器外壳");
    event.rename("block.gtceu.uv_machine_hull", "§3净涅§f机器外壳");
    event.rename("block.gtceu.uhv_machine_hull", "§4碎涅§f机器外壳");
    event.rename("block.gtceu.uev_machine_hull", "§a空涅§f机器外壳");
    event.rename("block.gtceu.uiv_machine_hull", "§2空灵§f机器外壳");
    event.rename("block.gtceu.uxv_machine_hull", "§e空玄§f机器外壳");
    event.rename("block.gtceu.opv_machine_hull", "§9§l空劫§f机器外壳");
    event.rename("block.gtceu.max_machine_hull", "§c§l踏天§f机器外壳");

    // 输入总线
    event.rename("block.gtceu.ulv_input_bus", "§8凝气§r输入总线");
    event.rename("block.gtceu.lv_input_bus", "§7筑基§r输入总线");
    event.rename("block.gtceu.mv_input_bus", "§b结丹§r输入总线");
    event.rename("block.gtceu.hv_input_bus", "§6元婴§r输入总线");
    event.rename("block.gtceu.ev_input_bus", "§5化神§r输入总线");
    event.rename("block.gtceu.iv_input_bus", "§9婴变§r输入总线");
    event.rename("block.gtceu.luv_input_bus", "§d问鼎§r输入总线");
    event.rename("block.gtceu.zpm_input_bus", "§c窥涅§r输入总线");
    event.rename("block.gtceu.uv_input_bus", "§3净涅§r输入总线");
    event.rename("block.gtceu.uhv_input_bus", "§4碎涅§r输入总线");
    event.rename("block.gtceu.uev_input_bus", "§a空涅§r输入总线");
    event.rename("block.gtceu.uiv_input_bus", "§2空灵§r输入总线");
    event.rename("block.gtceu.uxv_input_bus", "§e空玄§r输入总线");
    event.rename("block.gtceu.opv_input_bus", "§9§l空劫§r输入总线");
    event.rename("block.gtceu.max_input_bus", "§c§l踏天§r输入总线");

    // 输出总线
    event.rename("block.gtceu.ulv_output_bus", "§8凝气§r输出总线");
    event.rename("block.gtceu.lv_output_bus", "§7筑基§r输出总线");
    event.rename("block.gtceu.mv_output_bus", "§b结丹§r输出总线");
    event.rename("block.gtceu.hv_output_bus", "§6元婴§r输出总线");
    event.rename("block.gtceu.ev_output_bus", "§5化神§r输出总线");
    event.rename("block.gtceu.iv_output_bus", "§9婴变§r输出总线");
    event.rename("block.gtceu.luv_output_bus", "§d问鼎§r输出总线");
    event.rename("block.gtceu.zpm_output_bus", "§c窥涅§r输出总线");
    event.rename("block.gtceu.uv_output_bus", "§3净涅§r输出总线");
    event.rename("block.gtceu.uhv_output_bus", "§4碎涅§r输出总线");
    event.rename("block.gtceu.uev_output_bus", "§a空涅§r输出总线");
    event.rename("block.gtceu.uiv_output_bus", "§2空灵§r输出总线");
    event.rename("block.gtceu.uxv_output_bus", "§e空玄§r输出总线");
    event.rename("block.gtceu.opv_output_bus", "§9§l空劫§r输出总线");
    event.rename("block.gtceu.max_output_bus", "§c§l踏天§r输出总线");

    // 输入仓
    event.rename("block.gtceu.ulv_input_hatch", "§8凝气§r输入仓");
    event.rename("block.gtceu.lv_input_hatch", "§7筑基§r输入仓");
    event.rename("block.gtceu.mv_input_hatch", "§b结丹§r输入仓");
    event.rename("block.gtceu.hv_input_hatch", "§6元婴§r输入仓");
    event.rename("block.gtceu.ev_input_hatch", "§5化神§r输入仓");
    event.rename("block.gtceu.iv_input_hatch", "§9婴变§r输入仓");
    event.rename("block.gtceu.luv_input_hatch", "§d问鼎§r输入仓");
    event.rename("block.gtceu.zpm_input_hatch", "§c窥涅§r输入仓");
    event.rename("block.gtceu.uv_input_hatch", "§3净涅§r输入仓");
    event.rename("block.gtceu.uhv_input_hatch", "§4碎涅§r输入仓");
    event.rename("block.gtceu.uev_input_hatch", "§a空涅§r输入仓");
    event.rename("block.gtceu.uiv_input_hatch", "§2空灵§r输入仓");
    event.rename("block.gtceu.uxv_input_hatch", "§e空玄§r输入仓");
    event.rename("block.gtceu.opv_input_hatch", "§9§l空劫§r输入仓");
    event.rename("block.gtceu.max_input_hatch", "§c§l踏天§r输入仓");

    // 输出仓
    event.rename("block.gtceu.ulv_output_hatch", "§8凝气§r输出仓");
    event.rename("block.gtceu.lv_output_hatch", "§7筑基§r输出仓");
    event.rename("block.gtceu.mv_output_hatch", "§b结丹§r输出仓");
    event.rename("block.gtceu.hv_output_hatch", "§6元婴§r输出仓");
    event.rename("block.gtceu.ev_output_hatch", "§5化神§r输出仓");
    event.rename("block.gtceu.iv_output_hatch", "§9婴变§r输出仓");
    event.rename("block.gtceu.luv_output_hatch", "§d问鼎§r输出仓");
    event.rename("block.gtceu.zpm_output_hatch", "§c窥涅§r输出仓");
    event.rename("block.gtceu.uv_output_hatch", "§3净涅§r输出仓");
    event.rename("block.gtceu.uhv_output_hatch", "§4碎涅§r输出仓");
    event.rename("block.gtceu.uev_output_hatch", "§a空涅§r输出仓");
    event.rename("block.gtceu.uiv_output_hatch", "§2空灵§r输出仓");
    event.rename("block.gtceu.uxv_output_hatch", "§e空玄§r输出仓");
    event.rename("block.gtceu.opv_output_hatch", "§9§l空劫§r输出仓");
    event.rename("block.gtceu.max_output_hatch", "§c§l踏天§r输出仓");

    // 能源仓
    event.rename("block.gtceu.ulv_energy_input_hatch", "§8凝气§r能源仓");
    event.rename("block.gtceu.lv_energy_input_hatch", "§7筑基§r能源仓");
    event.rename("block.gtceu.mv_energy_input_hatch", "§b结丹§r能源仓");
    event.rename("block.gtceu.hv_energy_input_hatch", "§6元婴§r能源仓");
    event.rename("block.gtceu.ev_energy_input_hatch", "§5化神§r能源仓");
    event.rename("block.gtceu.iv_energy_input_hatch", "§9婴变§r能源仓");
    event.rename("block.gtceu.luv_energy_input_hatch", "§d问鼎§r能源仓");
    event.rename("block.gtceu.zpm_energy_input_hatch", "§c窥涅§r能源仓");
    event.rename("block.gtceu.uv_energy_input_hatch", "§3净涅§r能源仓");
    event.rename("block.gtceu.uhv_energy_input_hatch", "§4碎涅§r能源仓");
    event.rename("block.gtceu.uev_energy_input_hatch", "§a空涅§r能源仓");
    event.rename("block.gtceu.uiv_energy_input_hatch", "§2空灵§r能源仓");
    event.rename("block.gtceu.uxv_energy_input_hatch", "§e空玄§r能源仓");
    event.rename("block.gtceu.opv_energy_input_hatch", "§9§l空劫§r能源仓");
    event.rename("block.gtceu.max_energy_input_hatch", "§c§l踏天§r能源仓");

    // 动力仓
    event.rename("block.gtceu.ulv_energy_output_hatch", "§8凝气§r动力仓");
    event.rename("block.gtceu.lv_energy_output_hatch", "§7筑基§r动力仓");
    event.rename("block.gtceu.mv_energy_output_hatch", "§b结丹§r动力仓");
    event.rename("block.gtceu.hv_energy_output_hatch", "§6元婴§r动力仓");
    event.rename("block.gtceu.ev_energy_output_hatch", "§5化神§r动力仓");
    event.rename("block.gtceu.iv_energy_output_hatch", "§9婴变§r动力仓");
    event.rename("block.gtceu.luv_energy_output_hatch", "§d问鼎§r动力仓");
    event.rename("block.gtceu.zpm_energy_output_hatch", "§c窥涅§r动力仓");
    event.rename("block.gtceu.uv_energy_output_hatch", "§3净涅§r动力仓");
    event.rename("block.gtceu.uhv_energy_output_hatch", "§4碎涅§r动力仓");
    event.rename("block.gtceu.uev_energy_output_hatch", "§a空涅§r动力仓");
    event.rename("block.gtceu.uiv_energy_output_hatch", "§2空灵§r动力仓");
    event.rename("block.gtceu.uxv_energy_output_hatch", "§e空玄§r动力仓");
    event.rename("block.gtceu.opv_energy_output_hatch", "§9§l空劫§r动力仓");
    event.rename("block.gtceu.max_energy_output_hatch", "§c§l踏天§r动力仓");

    // 电池箱
    event.rename("block.gtceu.ulv_battery_buffer_4x", "4x§8凝气§r电池箱（§8凝气§r）");
    event.rename("block.gtceu.lv_battery_buffer_4x", "4x§7筑基§r电池箱（§7筑基§r）");
    event.rename("block.gtceu.mv_battery_buffer_4x", "4x§b结丹§r电池箱（§b结丹§r）");
    event.rename("block.gtceu.hv_battery_buffer_4x", "4x§6元婴§r电池箱（§6元婴§r）");
    event.rename("block.gtceu.ev_battery_buffer_4x", "4x§5化神§r电池箱（§5化神§r）");
    event.rename("block.gtceu.iv_battery_buffer_4x", "4x§9婴变§r电池箱（§9婴变§r）");
    event.rename("block.gtceu.luv_battery_buffer_4x", "4x§d问鼎§r电池箱（§d问鼎§r）");
    event.rename("block.gtceu.zpm_battery_buffer_4x", "4x§c窥涅§r电池箱（§c窥涅§r）");
    event.rename("block.gtceu.uv_battery_buffer_4x", "4x§3净涅§r电池箱（§3净涅§r）");
    event.rename("block.gtceu.uhv_battery_buffer_4x", "4x§4碎涅§r电池箱（§4碎涅§r）");
    event.rename("block.gtceu.uev_battery_buffer_4x", "4x§a空涅§r电池箱（§a空涅§r）");
    event.rename("block.gtceu.uiv_battery_buffer_4x", "4x§2空灵§r电池箱（§2空灵§r）");
    event.rename("block.gtceu.uxv_battery_buffer_4x", "4x§e空玄§r电池箱（§e空玄§r）");
    event.rename("block.gtceu.opv_battery_buffer_4x", "4x§9过载压§r电池箱（§9§l空劫§r）");
    event.rename("block.gtceu.max_battery_buffer_4x", "4x§c上限压§r电池箱（§c§l踏天§r）");

    // 充电箱
    event.rename("block.gtceu.ulv_charger_4x", "4x§8凝气§r闪聚充电箱（§8凝气§r）");
    event.rename("block.gtceu.lv_charger_4x", "4x§7筑基§r闪聚充电箱（§7筑基§r）");
    event.rename("block.gtceu.mv_charger_4x", "4x§b结丹§r闪聚充电箱（§b结丹§r）");
    event.rename("block.gtceu.hv_charger_4x", "4x§6元婴§r闪聚充电箱（§6元婴§r）");
    event.rename("block.gtceu.ev_charger_4x", "4x§5化神§r闪聚充电箱（§5化神§r）");
    event.rename("block.gtceu.iv_charger_4x", "4x§9婴变§r闪聚充电箱（§9婴变§r）");
    event.rename("block.gtceu.luv_charger_4x", "4x§d问鼎§r闪聚充电箱（§d问鼎§r）");
    event.rename("block.gtceu.zpm_charger_4x", "4x§c窥涅§r闪聚充电箱（§c窥涅§r）");
    event.rename("block.gtceu.uv_charger_4x", "4x§3净涅§r闪聚充电箱（§3净涅§r）");
    event.rename("block.gtceu.uhv_charger_4x", "4x§4碎涅§r闪聚充电箱（§4碎涅§r）");
    event.rename("block.gtceu.uev_charger_4x", "4x§a空涅§r闪聚充电箱（§a空涅§r）");
    event.rename("block.gtceu.uiv_charger_4x", "4x§2空灵§r闪聚充电箱（§2空灵§r）");
    event.rename("block.gtceu.uxv_charger_4x", "4x§e空玄§r闪聚充电箱（§e空玄§r）");
    event.rename("block.gtceu.opv_charger_4x", "4x§9过载压§r闪聚充电箱（§9§l空劫§r）");
    event.rename("block.gtceu.max_charger_4x", "4x§c上限压§r闪聚充电箱（§c§l踏天§r）");

    // 线圈
    event.rename("item.gtceu.ulv_voltage_coil", "凝气线圈");
    event.rename("item.gtceu.lv_voltage_coil", "筑基线圈");
    event.rename("item.gtceu.mv_voltage_coil", "结丹线圈");
    event.rename("item.gtceu.hv_voltage_coil", "元婴线圈");
    event.rename("item.gtceu.ev_voltage_coil", "化神线圈");
    event.rename("item.gtceu.iv_voltage_coil", "婴变线圈");
    event.rename("item.gtceu.luv_voltage_coil", "问鼎线圈");
    event.rename("item.gtceu.zpm_voltage_coil", "窥涅线圈");
    event.rename("item.gtceu.uv_voltage_coil", "净涅线圈");
    event.rename("item.gtceu.uhv_voltage_coil", "碎涅线圈");
    event.rename("item.gtceu.uev_voltage_coil", "空涅线圈");
    event.rename("item.gtceu.uiv_voltage_coil", "空灵线圈");
    event.rename("item.gtceu.uxv_voltage_coil", "空玄线圈");
    event.rename("item.gtceu.opv_voltage_coil", "空劫线圈");
    event.rename("item.gtceu.max_voltage_coil", "踏天线圈");

    // 太阳能板
    event.rename("item.gtceu.ulv_solar_panel", "凝气太阳能板（§8凝气§r）");
    event.rename("item.gtceu.lv_solar_panel", "筑基太阳能板（§7筑基§r）");
    event.rename("item.gtceu.mv_solar_panel", "结丹太阳能板（§b结丹§r）");
    event.rename("item.gtceu.hv_solar_panel", "元婴太阳能板（§6元婴§r）");
    event.rename("item.gtceu.ev_solar_panel", "化神太阳能板（§5化神§r）");
    event.rename("item.gtceu.iv_solar_panel", "婴变太阳能板（§9婴变§r）");
    event.rename("item.gtceu.luv_solar_panel", "问鼎太阳能板（§d问鼎§r）");
    event.rename("item.gtceu.zpm_solar_panel", "窥涅太阳能板（§c窥涅§r）");
    event.rename("item.gtceu.uv_solar_panel", "净涅太阳能板（§3净涅§r）");

    // 传送带
    event.rename("item.gtceu.lv_conveyor_module", "§7筑基§r传送带");
    event.rename("item.gtceu.mv_conveyor_module", "§b结丹§r传送带");
    event.rename("item.gtceu.hv_conveyor_module", "§6元婴§r传送带");
    event.rename("item.gtceu.ev_conveyor_module", "§5化神§r传送带");
    event.rename("item.gtceu.iv_conveyor_module", "§9婴变§r传送带");
    event.rename("item.gtceu.luv_conveyor_module", "§d问鼎§r传送带");
    event.rename("item.gtceu.zpm_conveyor_module", "§c窥涅§r传送带");
    event.rename("item.gtceu.uv_conveyor_module", "§3净涅§r传送带");
    event.rename("item.gtceu.uhv_conveyor_module", "§4碎涅§r传送带");
    event.rename("item.gtceu.uev_conveyor_module", "§a空涅§r传送带");
    event.rename("item.gtceu.uiv_conveyor_module", "§2空灵§r传送带");
    event.rename("item.gtceu.uxv_conveyor_module", "§e空玄§r传送带");
    event.rename("item.gtceu.opv_conveyor_module", "§9§l空劫§r传送带");

    // 电动马达
    event.rename("item.gtceu.lv_electric_motor", "§7筑基§r电动马达");
    event.rename("item.gtceu.mv_electric_motor", "§b结丹§r电动马达");
    event.rename("item.gtceu.hv_electric_motor", "§6元婴§r电动马达");
    event.rename("item.gtceu.ev_electric_motor", "§5化神§r电动马达");
    event.rename("item.gtceu.iv_electric_motor", "§9婴变§r电动马达");
    event.rename("item.gtceu.luv_electric_motor", "§d问鼎§r电动马达");
    event.rename("item.gtceu.zpm_electric_motor", "§c窥涅§r电动马达");
    event.rename("item.gtceu.uv_electric_motor", "§3净涅§r电动马达");
    event.rename("item.gtceu.uhv_electric_motor", "§4碎涅§r电动马达");
    event.rename("item.gtceu.uev_electric_motor", "§a空涅§r电动马达");
    event.rename("item.gtceu.uiv_electric_motor", "§2空灵§r电动马达");
    event.rename("item.gtceu.uxv_electric_motor", "§e空玄§r电动马达");
    event.rename("item.gtceu.opv_electric_motor", "§9§l空劫§r电动马达");

    // 电动泵
    event.rename("item.gtceu.lv_electric_pump", "§7筑基§r电动泵");
    event.rename("item.gtceu.mv_electric_pump", "§b结丹§r电动泵");
    event.rename("item.gtceu.hv_electric_pump", "§6元婴§r电动泵");
    event.rename("item.gtceu.ev_electric_pump", "§5化神§r电动泵");
    event.rename("item.gtceu.iv_electric_pump", "§9婴变§r电动泵");
    event.rename("item.gtceu.luv_electric_pump", "§d问鼎§r电动泵");
    event.rename("item.gtceu.zpm_electric_pump", "§c窥涅§r电动泵");
    event.rename("item.gtceu.uv_electric_pump", "§3净涅§r电动泵");
    event.rename("item.gtceu.uhv_electric_pump", "§4碎涅§r电动泵");
    event.rename("item.gtceu.uev_electric_pump", "§a空涅§r电动泵");
    event.rename("item.gtceu.uiv_electric_pump", "§2空灵§r电动泵");
    event.rename("item.gtceu.uxv_electric_pump", "§e空玄§r电动泵");
    event.rename("item.gtceu.opv_electric_pump", "§9§l空劫§r电动泵");

    // 机械臂
    event.rename("item.gtceu.lv_robot_arm", "§7筑基§r机械臂");
    event.rename("item.gtceu.mv_robot_arm", "§b结丹§r机械臂");
    event.rename("item.gtceu.hv_robot_arm", "§6元婴§r机械臂");
    event.rename("item.gtceu.ev_robot_arm", "§5化神§r机械臂");
    event.rename("item.gtceu.iv_robot_arm", "§9婴变§r机械臂");
    event.rename("item.gtceu.luv_robot_arm", "§d问鼎§r机械臂");
    event.rename("item.gtceu.zpm_robot_arm", "§c窥涅§r机械臂");
    event.rename("item.gtceu.uv_robot_arm", "§3净涅§r机械臂");
    event.rename("item.gtceu.uhv_robot_arm", "§4碎涅§r机械臂");
    event.rename("item.gtceu.uev_robot_arm", "§a空涅§r机械臂");
    event.rename("item.gtceu.uiv_robot_arm", "§2空灵§r机械臂");
    event.rename("item.gtceu.uxv_robot_arm", "§e空玄§r机械臂");
    event.rename("item.gtceu.opv_robot_arm", "§9§l空劫§r机械臂");

    // 发射器
    event.rename("item.gtceu.lv_emitter", "§7筑基§r发射器");
    event.rename("item.gtceu.mv_emitter", "§b结丹§r发射器");
    event.rename("item.gtceu.hv_emitter", "§6元婴§r发射器");
    event.rename("item.gtceu.ev_emitter", "§5化神§r发射器");
    event.rename("item.gtceu.iv_emitter", "§9婴变§r发射器");
    event.rename("item.gtceu.luv_emitter", "§d问鼎§r发射器");
    event.rename("item.gtceu.zpm_emitter", "§c窥涅§r发射器");
    event.rename("item.gtceu.uv_emitter", "§3净涅§r发射器");
    event.rename("item.gtceu.uhv_emitter", "§4碎涅§r发射器");
    event.rename("item.gtceu.uev_emitter", "§a空涅§r发射器");
    event.rename("item.gtceu.uiv_emitter", "§2空灵§r发射器");
    event.rename("item.gtceu.uxv_emitter", "§e空玄§r发射器");
    event.rename("item.gtceu.opv_emitter", "§9§l空劫§r发射器");

    // 传感器
    event.rename("item.gtceu.lv_sensor", "§7筑基§r传感器");
    event.rename("item.gtceu.mv_sensor", "§b结丹§r传感器");
    event.rename("item.gtceu.hv_sensor", "§6元婴§r传感器");
    event.rename("item.gtceu.ev_sensor", "§5化神§r传感器");
    event.rename("item.gtceu.iv_sensor", "§9婴变§r传感器");
    event.rename("item.gtceu.luv_sensor", "§d问鼎§r传感器");
    event.rename("item.gtceu.zpm_sensor", "§c窥涅§r传感器");
    event.rename("item.gtceu.uv_sensor", "§3净涅§r传感器");
    event.rename("item.gtceu.uhv_sensor", "§4碎涅§r传感器");
    event.rename("item.gtceu.uev_sensor", "§a空涅§r传感器");
    event.rename("item.gtceu.uiv_sensor", "§2空灵§r传感器");
    event.rename("item.gtceu.uxv_sensor", "§e空玄§r传感器");
    event.rename("item.gtceu.opv_sensor", "§9§l空劫§r传感器");

    // 力场发生器
    event.rename("item.gtceu.lv_field_generator", "§7筑基§r力场发生器");
    event.rename("item.gtceu.mv_field_generator", "§b结丹§r力场发生器");
    event.rename("item.gtceu.hv_field_generator", "§6元婴§r力场发生器");
    event.rename("item.gtceu.ev_field_generator", "§5化神§r力场发生器");
    event.rename("item.gtceu.iv_field_generator", "§9婴变§r力场发生器");
    event.rename("item.gtceu.luv_field_generator", "§d问鼎§r力场发生器");
    event.rename("item.gtceu.zpm_field_generator", "§c窥涅§r力场发生器");
    event.rename("item.gtceu.uv_field_generator", "§3净涅§r力场发生器");
    event.rename("item.gtceu.uhv_field_generator", "§4碎涅§r力场发生器");
    event.rename("item.gtceu.uev_field_generator", "§a空涅§r力场发生器");
    event.rename("item.gtceu.uiv_field_generator", "§2空灵§r力场发生器");
    event.rename("item.gtceu.uxv_field_generator", "§e空玄§r力场发生器");
    event.rename("item.gtceu.opv_field_generator", "§9§l空劫§r力场发生器");

    // 流体校准器
    event.rename("item.gtceu.lv_fluid_regulator", "§7筑基§r流体校准器");
    event.rename("item.gtceu.mv_fluid_regulator", "§b结丹§r流体校准器");
    event.rename("item.gtceu.hv_fluid_regulator", "§6元婴§r流体校准器");
    event.rename("item.gtceu.ev_fluid_regulator", "§5化神§r流体校准器");
    event.rename("item.gtceu.iv_fluid_regulator", "§9婴变§r流体校准器");
    event.rename("item.gtceu.luv_fluid_regulator", "§d问鼎§r流体校准器");
    event.rename("item.gtceu.zpm_fluid_regulator", "§c窥涅§r流体校准器");
    event.rename("item.gtceu.uv_fluid_regulator", "§3净涅§r流体校准器");
    event.rename("item.gtceu.uhv_fluid_regulator", "§4碎涅§r流体校准器");
    event.rename("item.gtceu.uev_fluid_regulator", "§a空涅§r流体校准器");
    event.rename("item.gtceu.uiv_fluid_regulator", "§2空灵§r流体校准器");
    event.rename("item.gtceu.uxv_fluid_regulator", "§e空玄§r流体校准器");
    event.rename("item.gtceu.opv_fluid_regulator", "§9§l空劫§r流体校准器");

    // 电池外壳提示（可选）
    event.rename("item.gtceu.lv_battery_hull", "小型电池外壳");
    event.rename("item.gtceu.lv_battery_hull.tooltip", "§7一个空的§7筑基§7电池外壳");
    event.rename("item.gtceu.mv_battery_hull", "中型电池外壳");
    event.rename("item.gtceu.mv_battery_hull.tooltip", "§7一个空的§b结丹§7电池外壳");
    event.rename("item.gtceu.hv_battery_hull", "大型电池外壳");
    event.rename("item.gtceu.hv_battery_hull.tooltip", "§7一个空的§6元婴§7电池外壳");
    event.rename("item.gtceu.ev_battery_hull", "小型钒电池外壳");
    event.rename("item.gtceu.ev_battery_hull.tooltip", "§7一个空的§5化神§7电池外壳");
    event.rename("item.gtceu.iv_battery_hull", "中型钒电池外壳");
    event.rename("item.gtceu.iv_battery_hull.tooltip", "§7一个空的§1婴变§7电池外壳");
    event.rename("item.gtceu.luv_battery_hull", "大型钒电池外壳");
    event.rename("item.gtceu.luv_battery_hull.tooltip", "§7一个空的§d问鼎§r电池外壳");
    event.rename("item.gtceu.zpm_battery_hull", "中型超能硅岩电池外壳");
    event.rename("item.gtceu.zpm_battery_hull.tooltip", "§7一个空的§f窥涅§7电池外壳");
    event.rename("item.gtceu.uv_battery_hull", "大型超能硅岩电池外壳");
    event.rename("item.gtceu.uv_battery_hull.tooltip", "§7一个空的§3净涅§7电池外壳");

    // 工具提示中的电压部分（保持占位符）
    event.rename("gtceu.universal.tooltip.voltage_in", "§a输入电压：§f%d EU/t（%s§f）");
    event.rename("gtceu.universal.tooltip.voltage_out", "§a输出电压：§f%d EU/t（%s§f）");
    event.rename("gtceu.universal.tooltip.max_voltage_in", "§a最大输入电压：§f%d（%s§f）");
    event.rename("gtceu.universal.tooltip.max_voltage_out", "§a最大输出电压：§f%d（%s§f）");
    event.rename("gtceu.universal.tooltip.energy_tier_range", "§a适配电压等级：§f%s§f-%s");
});