
#Graphics
[graphics]
	#Intensity of screenshake.
	#Range: 0.0 ~ 10.0
	screenshakeIntensity = 1.0
	#Enable weather render fix in fabulous graphics.
	fabulousWeatherFix = true
	#Enable fancy fog.
	fancyFog = true
	#Intensity of fancy fog.
	#Range: 0.0 ~ 100.0
	fancyFogntensity = 2.0
	#Enable sphere shape of fancy fog.
	fancyFogSphere = false
	#Enable dependence of clouds on day time.
	daylightClouds = true
	#Enable dependence of clouds on day time when daylight cycle disabled.
	daylightCloudsIgnore = false

	#Particles
	[graphics.particles]
		#Enable dropping items particles.
		itemParticle = true
		#Enable items particles in GUI.
		itemGuiParticle = true
		#Enable blood particles in case of damage.
		bloodParticle = false
		#Enable custom effect of lightning bolt.
		lightningBoltEffect = true
		#Enable custom effect of explosion.
		explosionEffect = true
		#Enable screenshake for custom effect of explosion.
		explosionEffectScreenshake = true

	#Shaders
	[graphics.shaders]
		#Enable Rain Fog effect post process shader.
		rainFogShader = true
		#Intensity of Rain Fog effect post process shader.
		#Range: 0.0 ~ 2.0
		rainFogShaderIntensity = 0.3
		#Intensity of Thunder Fog effect post process shader.
		#Range: 0.0 ~ 2.0
		thunderFogShaderIntensity = 0.1
		#Intensity of Thunder Fog fade effect post process shader.
		#Range: 0.0 ~ 1.0
		thunderFogFadeShaderIntensity = 0.25
		#Enable noise for Rain Fog effect.
		rainFogShaderNoise = true
		#Enable Interleaved Gradient Noise for Rain Fog effect.
		rainFogShaderIGN = true

#Menu
[menu]
	#Fluffy Fur Panorama.
	panorama = "minecraft:vanilla"
	#Enable Fluffy Fur menu button.
	menuButton = true
	#Fluffy Fur menu button row.
	#Range: 0 ~ 4
	menuButtonRow = 3
	#Fluffy Fur menu button X offset with row.
	menuButtonRowXOffset = 4
	#Fluffy Fur menu button X offset.
	menuButtonXOffset = 0
	#Fluffy Fur menu button Y offset.
	menuButtonYOffset = 0
	#Enable logo in Fluffy Fur Panorama.
	panoramaLogo = true
	#Enable music in Fluffy Fur Panorama.
	panoramaMusic = true

