#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 29 22:38:35 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Solas Shader V3.2.zip
enableShaders=false
