
["维度生成设置"]
	#边框方块，若不存在则使用蓝色羊毛
	"边框方块" = "useless_mod:aqua_glow_plastic"
	#填充方块，若不存在则使用白色羊毛
	"填充方块" = "useless_mod:white_glow_plastic"
	#中心方块，若不存在则使用灰色羊毛
	"中心方块" = "useless_mod:light_gray_glow_plastic"
	#塑料平台生成层数
	#Range: 1 ~ 256
	"塑料平台层数" = 69
	#平台起始Y值(若无基岩实际会比该数值高1)
	#Range: -64 ~ 256
	"平台起始Y值" = -64
	#是否生成基岩层，默认生成
	"生成基岩层" = true

["游戏机制设置"]
	#植物盆生长倍率 - 1.0为原版速度，2.0为2倍速度
	#Range: > 1
	"植物盆生长倍率（仅限非附属的植物盆）" = 1
	#矩阵样板槽位倍数 - 减少数量时请保持槽位空！否则可能会造成样板丢失
	#Range: 1 ~ 100
	"矩阵样板槽位倍数" = 1

	["游戏机制设置"."牛排工具设置"]
		#连锁挖掘的X轴范围半径
		#Range: 1 ~ 255
		"连锁挖掘X轴范围" = 8
		#连锁挖掘的Y轴范围半径
		#Range: 1 ~ 255
		"连锁挖掘Y轴范围" = 8
		#连锁挖掘的Z轴范围半径
		#Range: 1 ~ 255
		"连锁挖掘Z轴范围" = 8
		#连锁挖掘的最大方块数量
		#Range: 1 ~ 10000
		"连锁挖掘最大方块数量" = 1000
		#牛排工具时运附魔等级
		#Range: 1 ~ 127
		"牛排工具时运等级" = 10
		#牛排工具抢夺附魔等级
		#Range: 1 ~ 127
		"牛排工具抢夺等级" = 10

["Mekanism升级设置"]
	#速度升级增强倍率
	#Range: > 1
	"速度平均每8个升级最终效果乘以一次该倍率" = 1
	#能量升级节电增强倍率
	#Range: > 1
	"节电平均每8个升级最终效果乘以一次该倍率" = 1
	#能量升级储电增强倍率
	#Range: > 1
	"储电平均每8个升级最终效果乘以一次该倍率" = 1
	#机器可接受的最大速度/能量升级数量，重启游戏生效
	#Range: 1 ~ 64
	"最大升级数量" = 16

["效果设置"]
	#是否启用药水效果（饱和、生命恢复、夜视、抗火、水下呼吸、抗性提升）
	"启用药水效果" = true
	#是否启用飞行效果
	"启用飞行效果" = true

